### ISSUE TITLE
Tooltip text is not visible

### ISSUE THREAD

**Issue by kirizdev** [maximilionus/telegram-dark-shell#10]
![image](https://user-images.githubusercontent.com/91323838/211193424-d968f28a-f0cd-405c-9476-52881ffc76e7.png)
Here is how tooltip text looks. I'm using Telegram Desktop

**Comment by maximilionus** [comment]
Issue confirmed, thanks for the report. I'll take a look at it a little later.

**Comment by maximilionus** [comment]
Issue fixed in 0568f686304e29559a349969bedc14e62d647edf on `development` branch and update is already uploaded to the cloud version of theme.
