### ISSUE TITLE
Chat Export Theme

### ISSUE THREAD

**Issue by timea-techgirl** [maximilionus/telegram-dark-shell#8]
Hey! Thanks for the nice themes. :) I would like to kindly request a dark theme for the exported chat history. Currently it's blinding white and I requested Telegram countless times for a dark version of chat export. They did nothing about it. I edited the colours in style.css and managed to turn the history dark but I'm sure you can do it better. Here is the original css file.

[style.zip](https://github.com/maximilionus/telegram-dark-shell/files/9484792/style.zip)

Hope you have time to do it. Thanks! :)

**Comment by maximilionus** [comment]
Hi @timea-techgirl. That's a nice request, but currently I don't have much time to work on such projects. However, I can suggest you using the [Dark Reader](https://darkreader.org/) extension for your browser. It will require some more actions if you're using a chromium based browser - extension should be allowed to read `file://` URLs to interact with local files. You can find how do this [here](https://github.com/darkreader/darkreader/issues/475#issuecomment-387584506).

The final result will look something like this: 
![image](https://user-images.githubusercontent.com/29492157/188323403-7aff4476-fc2f-4b95-a354-f3ce8b08e2df.png)

**Comment by timea-techgirl** [comment]
Hey! I am talking about exporting history from here. Inside a chat, 3 dots > Export chat history.

![image](https://user-images.githubusercontent.com/7058205/188323606-cf3e63db-d213-49ea-a520-cca5cbdb2694.png)

I already have file URLs enabled for dark reader but it doesn't work.

But thanks for your response.

**Comment by maximilionus** [comment]
@timea-techgirl strange it doesn't work... Are you sure you enabled the extension in its pop-up menu? You should enable it globally or add the full path to directory *(like this: `file:///H:/Download/Telegram%20Desktop/ChatExport_2022-09-04`)* to **Site list** tab.

Here how it looks for me
![image](https://user-images.githubusercontent.com/29492157/188324063-0c152484-c8c1-40ef-a910-9ebbb495f1da.png)

**Comment by timea-techgirl** [comment]
Thanks, managed to make it work. Had to reset the extension. :)
Added `file://` to the inverted list and it works now.
